# version: '3.8'

services:
  backend:
    build:
      context: ./ai_chatbot_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./ai_chatbot_backend/.env
    volumes:
      - ./ai_chatbot_backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./ai_chatbot_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ai_chatbot_frontend:/app
    restart: unless-stopped
